### ISSUE TITLE
Deprecate RouteHash.elm

### ISSUE THREAD

**Issue by amitaibu** [rgrempel/elm-route-hash#16]
As a user of the 1.x version, doing the transition to 2.x (RouteUrl) wasn't very hard - and when we'll the examples use it, it will be even easier.

So I think it's better to keep just one option - the improved one.

(I'm working on a post that will mention this module as a great routing option, so thinking of lowering the barrier 😉 )

**Comment by rgrempel** [comment]
Yes, I think that makes sense -- I'm assuming you literally mean "deprecate", as in update the documentation to indicate that it is being retained as a transitional thing only, and will be removed in a future version.

I'd rather not delete it immediately, as I do like providing as much back-compat as possible, at least for a while.

**Comment by amitaibu** [comment]
👍

**Comment by rgrempel** [comment]
I've updated the documentation to do this.
