### ISSUE TITLE
Change name to elm-route-url

### ISSUE THREAD

**Issue by rgrempel** [rgrempel/elm-route-hash#17]
I'm planning to change the name of this repository to elm-route-url, to reflect the fact that the next version won't be limited to just the hash -- you will be able to route based on the full URL if you like.

Let me know if anyone has a better idea for a name ...

**Comment by amitaibu** [comment]
why not just `elm-route`?

**Comment by rgrempel** [comment]
There already is a [Bogdanp/elm-route](http://package.elm-lang.org/packages/Bogdanp/elm-route/latest) ...

**Comment by rgrempel** [comment]
So, the rename to elm-route-url is done. I re-published all the previous versions in the Elm package repository under the new name (as well as the new version).

Github does redirects for the old name, so installing elm-route-hash 1.x still works -- this shouldn't break anything for anyone.
