### ISSUE TITLE
Update sporto/erl dependency

### ISSUE THREAD

**Issue by rgrempel** [rgrempel/elm-route-hash#28]
The sporto/erl dependency changed in version 11 to use a `List (String, String)` instead of a `Dict` to keep track of the URL's query.

This makes sense, since the query can have the same key twice (unlike a `Dict`).

It turns out to require a major version bump here, because of the signature of various functions in `RouteUrl.Builder`.

So, I should take care of that -- otherwise, people who use rgrempel/elm-route-url wouldn't be able to upgrade sporto/erl to version 11 and beyond.

**Comment by robashton** [comment]
And sadly there are bugs in version 10 (see #30) so a +1 from me on this one :(

**Comment by MarkNijhof** [comment]
+1
