### ISSUE TITLE
Update for Elm 0.16

### ISSUE THREAD

**Issue by rgrempel** [rgrempel/elm-route-hash#7]
At the moment, I'm blocked on elm-history -- once that is updated, I can look at what is needed here.

**Comment by amitaibu** [comment]
Looking forward to it :)

**Comment by rgrempel** [comment]
So, I'm basically blocked on https://github.com/elm-lang/package.elm-lang.org/pull/124 or https://github.com/TheSeamau5/elm-history/pull/3 -- I suppose it doesn't matter to me which one gets accepted! It's hard to predict how long that will last.

If anyone just wants elm-route-hash running with 0.16, I can achieve that by putting the elm-history native code inside elm-route-hash -- the down-side is that I wouldn't be able to publish that to the package repository -- you'd have to install elm-route-hash manually, by copying it into your source code. So, I'm not eager to do that, but it's not hard for me to do if someone wants it.

**Comment by amitaibu** [comment]
@rgrempel I'd suggest, let's wait a week or so for your package to be published - the alternative of adding native to this lib isn't much nicer.

**Comment by rgrempel** [comment]
elm-community/elm-history has now been published:

http://package.elm-lang.org/packages/elm-community/elm-history/1.0.1/

So, I should have elm-route-hash updated soon.

**Comment by amitaibu** [comment]
Awesome!

**Comment by rgrempel** [comment]
The update has now been published in the package repository.
