### ISSUE TITLE
Collaborators

### ISSUE THREAD

**Issue by rgrempel** [rgrempel/elm-route-hash#9]
@amitaibu, I've added you as a collaborator on this repository -- I was thinking that it made sense to have more than one person with `commit` privileges for something that's being used. Let me know if that doesn't suit you :-)

**Comment by amitaibu** [comment]
wow! I probably _still_ don't deserve it since I haven't done any proper contribution (apart of telling everybody how cool it is), but much appreciated, and I hope to provide quality PRs in the future :)
